company_ticker_map = {
    # Indian Stocks (NSE)
    "reliance": "RELIANCE.NS",
    "tcs": "TCS.NS",
    "infosys": "INFY.NS",
    "hdfc bank": "HDFCBANK.NS",
    "icici bank": "ICICIBANK.NS",
    "hindustan unilever": "HINDUNILVR.NS",
    "itc": "ITC.NS",
    "state bank of india": "SBIN.NS",
    "kotak mahindra bank": "KOTAKBANK.NS",
    "larsen & toubro": "LT.NS",
    "bharti airtel": "BHARTIARTL.NS",
    "asian paints": "ASIANPAINT.NS",
    "hcl technologies": "HCLTECH.NS",
    "axis bank": "AXISBANK.NS",
    "maruti suzuki": "MARUTI.NS",
    "ntpc": "NTPC.NS",
    "bajaj finance": "BAJFINANCE.NS",
    "nestle india": "NESTLEIND.NS",
    "sun pharma": "SUNPHARMA.NS",
    "ultratech cement": "ULTRACEMCO.NS",
    "mahindra & mahindra": "M&M.NS",
    "power grid": "POWERGRID.NS",
    "titan": "TITAN.NS",
    "wipro": "WIPRO.NS",
    "tech mahindra": "TECHM.NS",
    "tata motors": "TATAMOTORS.NS",
    "bajaj auto": "BAJAJ-AUTO.NS",
    "dr reddy's laboratories": "DRREDDY.NS",
    "britannia": "BRITANNIA.NS",
    "coal india": "COALINDIA.NS",
    "hdfc life": "HDFCLIFE.NS",
    "sbi life": "SBILIFE.NS",
    "eicher motors": "EICHERMOT.NS",
    "indusind bank": "INDUSINDBK.NS",
    "hero motocorp": "HEROMOTOCO.NS",
    "cipla": "CIPLA.NS",
    "divis laboratories": "DIVISLAB.NS",
    "bajaj finserv": "BAJAJFINSV.NS",
    "grasim industries": "GRASIM.NS",
    "adani enterprises": "ADANIENT.NS",
    "adani ports": "ADANIPORTS.NS",
    "hdfc": "HDFC.NS",

   # U.S. Stocks (NASDAQ/NYSE)
    "apple": "AAPL",
    "microsoft": "MSFT",
    "amazon": "AMZN",
    "alphabet": "GOOGL",
    "google": "GOOGL",
    "meta": "META",
    "facebook": "META",
    "tesla": "TSLA",
    "nvidia": "NVDA",
    "netflix": "NFLX",
    "paypal": "PYPL",
    "intel": "INTC",
    "advanced micro devices": "AMD",
    "amd": "AMD",
    "qualcomm": "QCOM",
    "salesforce": "CRM",
    "oracle": "ORCL",
    "shopify": "SHOP",
    "snowflake": "SNOW",
    "zoom": "ZM",
    "coca cola": "KO",
    "pepsi": "PEP",
    "walmart": "WMT",
    "target": "TGT",
    "mcdonald's": "MCD",
    "disney": "DIS",
    "boeing": "BA",
    "chevron": "CVX",
    "exxonmobil": "XOM",
    "jpmorgan": "JPM",
    "bank of america": "BAC",
    "goldman sachs": "GS",
    "uber": "UBER",
    "lyft": "LYFT",
    "airbnb": "ABNB"
}

nse_sector_map = {
    "auto": ["M&M.NS", "MARUTI.NS", "TATAMOTORS.NS", "BAJAJ-AUTO.NS", "EICHERMOT.NS"],
    "bank": ["HDFCBANK.NS", "ICICIBANK.NS", "SBIN.NS", "KOTAKBANK.NS", "AXISBANK.NS"],
    "financial_services": ["BAJFINANCE.NS", "BAJAJFINSV.NS", "HDFCBANK.NS", "ICICIBANK.NS", "SBIN.NS"],
    "fmcg": ["HINDUNILVR.NS", "ITC.NS", "NESTLEIND.NS", "BRITANNIA.NS", "DABUR.NS"],
    "healthcare": ["SUNPHARMA.NS", "CIPLA.NS", "DRREDDY.NS", "DIVISLAB.NS", "AUROPHARMA.NS"],
    "technology": ["TCS.NS", "INFY.NS", "HCLTECH.NS", "WIPRO.NS", "TECHM.NS"],
    "media": ["ZEEL.NS", "SUNTV.NS", "INDIAVISION.NS", "TV18BRDCST.NS", "PVR.NS"],
    "metal": ["TATASTEEL.NS", "JSWSTEEL.NS", "HINDALCO.NS", "COALINDIA.NS", "VEDL.NS"],
    "pharma": ["SUNPHARMA.NS", "CIPLA.NS", "DRREDDY.NS", "DIVISLAB.NS", "LUPIN.NS"],
    "oil_and_gas": ["RELIANCE.NS", "ONGC.NS", "BPCL.NS", "IOC.NS", "GAIL.NS"],
    "500_healthcare": ["SUNPHARMA.NS", "CIPLA.NS", "DRREDDY.NS", "DIVISLAB.NS", "AUROPHARMA.NS"]
}


bse_sector_map = {
    "auto": ["M&M.BO", "MARUTI.BO", "TATAMOTORS.BO", "BAJAJ-AUTO.BO", "EICHERMOT.BO"],
    "bank": ["HDFCBANK.BO", "ICICIBANK.BO", "SBIN.BO", "KOTAKBANK.BO", "AXISBANK.BO"],
    "financial_services": ["BAJFINANCE.BO", "BAJAJFINSV.BO", "HDFCBANK.BO", "ICICIBANK.BO", "SBIN.BO"],
    "fmcg": ["HINDUNILVR.BO", "ITC.BO", "NESTLEIND.BO", "BRITANNIA.BO", "DABUR.BO"],
    "healthcare": ["SUNPHARMA.BO", "CIPLA.BO", "DRREDDY.BO", "DIVISLAB.BO", "AUROPHARMA.BO"],
    "it": ["TCS.BO", "INFY.BO", "HCLTECH.BO", "WIPRO.BO", "TECHM.BO"],
    "media": ["ZEEL.BO", "SUNTV.BO", "INDIAVISION.BO", "TV18BRDCST.BO", "PVR.BO"],
    "metal": ["TATASTEEL.BO", "JSWSTEEL.BO", "HINDALCO.BO", "COALINDIA.BO", "VEDL.BO"],
    "pharma": ["SUNPHARMA.BO", "CIPLA.BO", "DRREDDY.BO", "DIVISLAB.BO", "LUPIN.BO"],
    "oil_and_gas": ["RELIANCE.BO", "ONGC.BO", "BPCL.BO", "IOC.BO", "GAIL.BO"],
}


us_sector_map = {
    "technology": ["AAPL", "MSFT", "GOOGL", "AMZN", "NVDA"],
    "finance": ["JPM", "GS", "BAC", "WFC", "C"],
    "healthcare": ["PFE", "JNJ", "UNH", "MRK", "ABBV"],
    "consumer_discretionary": ["TSLA", "MCD", "SBUX", "NKE", "HD"],
    "consumer_staples": ["KO", "PEP", "WMT", "PG", "COST"],
    "energy": ["XOM", "CVX", "COP", "SLB", "PSX"],
    "industrial": ["BA", "CAT", "GE", "MMM", "HON"],
    "real_estate": ["PLD", "SPG", "AMT", "CCI", "EQIX"],
    "communication_services": ["NFLX", "META", "DIS", "T", "VZ"],
    "materials": ["LIN", "APD", "SHW", "ECL", "NUE"],
    "utilities": ["NEE", "DUK", "SO", "EXC", "AEP"],
}
